development:
  morphology: stem_en 
  mem_limit:  1024M
  bin_path: "/usr/bin"
  searchd_binary_name: "searchd"
  indexer_binary_name: "indexer"
  pid_file: <%=Rails.root%>/tmp/pids/searchd.<%=Rails.env%>.pid
